# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sig_terminal_cpp <- function(path, ws_xptr) {
    .Call(`_PathSignatuR_sig_terminal_cpp`, path, ws_xptr)
}

sig_batch_cpp <- function(paths, ws_xptr) {
    .Call(`_PathSignatuR_sig_batch_cpp`, paths, ws_xptr)
}

sig_path_cpp <- function(path, ws_xptr) {
    .Call(`_PathSignatuR_sig_path_cpp`, path, ws_xptr)
}

log_sig_path_cpp <- function(path, ws_xptr) {
    .Call(`_PathSignatuR_log_sig_path_cpp`, path, ws_xptr)
}

log_sig_terminal_cpp <- function(path, ws_xptr) {
    .Call(`_PathSignatuR_log_sig_terminal_cpp`, path, ws_xptr)
}

build_sig_workspace <- function(d, N) {
    .Call(`_PathSignatuR_build_sig_workspace`, d, N)
}

tensor_product_cpp <- function(a, b, ws_xptr) {
    .Call(`_PathSignatuR_tensor_product_cpp`, a, b, ws_xptr)
}

build_shuffle_workspace <- function(d, N) {
    .Call(`_PathSignatuR_build_shuffle_workspace`, d, N)
}

shuffle_product_cpp <- function(a, b, ws_xptr) {
    .Call(`_PathSignatuR_shuffle_product_cpp`, a, b, ws_xptr)
}

